### ISSUE TITLE
Crash after long run

### ISSUE THREAD

**Issue by BorisGerretzen** [akacdev/Certstream#2]
After running the application for 8+ hours I get an exception:
```csharp 
System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerBase.ChangeTimer(UInt32 dueTime, UInt32 period)
   at System.Threading.Timer.Change(Int32 dueTime, Int32 period)
   at System.Timers.Timer.UpdateTimer()
   at System.Timers.Timer.set_Interval(Double value)
```
It occurs at line 104 in Certstream.cs, 
```csharp 
Pinger.Interval = PingInterval;
```

**Comment by akacdev** [comment]
Fixed in v**1.0.3** (https://www.nuget.org/packages/Certstream/1.0.3)
